Commerce 12776
andrea-ale-sbarra/liferay-portal pull request #42
Opened 2023-11-17 15:50 UTC by andrea-ale-sbarra

2023-11-22 10:10 UTC, alessiorendina requested changes
@andrea-ale-sbarra Left some comments for you, thanks!

2023-11-22 10:10 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/edit_commerce_virtual_order_item_file_entry.jsp
> +<aui:script sandbox="<%= true %>">
Can we move this into a js file?

2023-11-22 10:10 UTC, alessiorendina commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/resources/META-INF/resources/edit_cpd_virtual_setting_file_entry.jsp
> +<aui:script sandbox="<%= true %>">
Can we move this into a js file?

2023-11-23 13:44 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-product-type-virtual-web/src/main/java/com/liferay/commerce/product/type/virtual/web/internal/frontend/view/table/CPDefinitionVirtualSettingTableFDSView.java
> +			"url", "url"
I asked David about this, he said that the URL makes sense

2023-11-23 13:45 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-media-impl/src/main/java/com/liferay/commerce/media/internal/servlet/CommerceMediaServlet.java
> +						"The file entry " + fileEntryId + " does not exist");
This message is already in, I've just reused what was already in.

2023-11-23 13:45 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-media-impl/src/main/java/com/liferay/commerce/media/internal/servlet/CommerceMediaServlet.java
> +						"The file entry " + fileEntryId + " does not exist");
This message is already in, I've just reused what was already in.

2023-11-23 13:46 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-product-type-virtual-api/bnd.bnd
> +Bundle-Version: 9.0.0
sure thing, I'll make a new PR out of this writing a new history..

2023-11-23 13:46 UTC, andrea-ale-sbarra commented on modules/apps/commerce/commerce-product-type-virtual-order-api/bnd.bnd
> +Bundle-Version: 9.0.0
sure thing, I'll make a new PR out of this writing a new history..

2023-12-01 10:03 UTC, closed without merging